active: "testnet"

mainnet:
  node: 
    lcd_server_endpoint: "http://172.16.0.60:1317"
    node_server_endpoint: "http://172.16.0.60:26657"
  web:
    port: 5001
  mysql:
    mysql_res : "hschain:hschain@tcp(192.168.15.99:3306)/hschain?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=true"


testnet:
  node: 
    #lcd_server_endpoint: "http://103.150.214.70:1317"
    #node_server_endpoint: "http://192.168.15.99:26657"
    #node_server_endpoint: "http://51.75.145.123:26657"
    lcd_server_endpoint: "http://127.0.0.1:1317"
    node_server_endpoint: "http://127.0.0.1:26657"
  web:
    port: 5001
  mysql:
   # mysql_res : "hschain:hschain@tcp(192.168.15.99:3306)/hschain?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=true"
    mysql_res : "root:mingshan@tcp(127.0.0.1:3306)/hschain?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=true"
