active: "testnet"

mainnet:
  node: 
    lcd_server_endpoint: "http://172.16.0.60:1317"
    node_server_endpoint: "http://172.16.0.60:26657"
    pri_server_endpoint: "https://wallet.hschain.io"
  web:
    ip: 127.0.0.1
    port: 5001
  mysql:
    mysql_res : "hschain:hschain@tcp(192.168.15.99:3306)/hschain?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=true"


testnet:
  node:
    #lcd_server_endpoint: "http://172.16.0.60:1317"
    #node_server_endpoint: "http://172.16.0.60:26657"
    #node_server_endpoint: "http://51.75.145.123:26657"
    lcd_server_endpoint: "https://scan.hschain.io/api/v2"
    node_server_endpoint: "http://8.210.85.143:26657"
    pri_server_endpoint: "https://wallet.hschain.io"
  web:
    port: 5002
  mysql:
   # mysql_res : "hschain:hschain@tcp(192.168.15.99:3306)/hschain?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=true"
    mysql_res : "hscan:123456@tcp(172.16.0.64:3306)/hscanTest?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=true"

hschain:
  addrss:
    destroy: "hsc19q4r9qu34ayjns0yx2jf06hudvesquvkd8swnm"
    supplement: "hsc1gqsymyueflxr3rrkumvc7q8g4nfc5yne8cvf97"